import { Link } from "react-router-dom";

const Privacy = () => {
  return (
    <div className="min-h-screen bg-black text-white flex flex-col items-center justify-start px-4 py-12">
      <div className="w-full max-w-2xl">
        <div className="mb-8">
          <Link
            to="/"
            className="inline-block text-blue-400 hover:text-blue-200 underline text-lg font-semibold transition-colors"
          >
            ← Back to Home
          </Link>
        </div>
        <h1 className="text-4xl font-bold mb-6 bg-gradient-to-r from-purple-400 via-blue-400 to-cyan-400 bg-clip-text text-transparent">
          Privacy Policy
        </h1>
        {/* Privacy policy content goes here */}
        <div className="bg-gray-900/60 rounded-lg p-6 shadow-xl min-h-[200px] space-y-6">
          <section>
            <p className="mb-2">
              This page is used to inform visitors regarding policies with the collection, use, and disclosure of Personal Information if anyone decided to use the application.
            </p>
            <p className="mb-2">
              The terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, which are accessible at PullBarPro unless otherwise defined in this Privacy Policy.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-2 text-purple-300">Information Collection and Use</h2>
            <p>
              The application does not collect any user-related data. The application's settings are saved on the user's device by means of macOS using UserDefaults or KeyChain.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-2 text-purple-300">Changes to This Privacy Policy</h2>
            <p>
              I may update our Privacy Policy from time to time. Thus, you are advised to review this page periodically for any changes. I will notify you of any changes by posting the new Privacy Policy on this page.
            </p>
            <p className="italic text-gray-400 mt-2">This policy is effective as of 2023-08-18</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-2 text-purple-300">Contact Us</h2>
            <p>
              If you have any questions or suggestions about my Privacy Policy, do not hesitate to contact me at{' '}
              <a href="https://pavelmakhov.com" className="text-blue-400 underline hover:text-blue-200" target="_blank" rel="noopener noreferrer">
                pavelmakhov.com
              </a>.
            </p>
          </section>

          <section className="pt-4 border-t border-gray-800 text-xs text-gray-400">
            <p>
              This privacy policy page was created at{' '}
              <a href="https://privacypolicytemplate.net" className="underline text-blue-400 hover:text-blue-200" target="_blank" rel="noopener noreferrer">
                privacypolicytemplate.net
              </a>{' '}and modified/generated by{' '}
              <a href="https://app-privacy-policy-generator.nisrulz.com/" className="underline text-blue-400 hover:text-blue-200" target="_blank" rel="noopener noreferrer">
                App Privacy Policy Generator
              </a>.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
};

export default Privacy;
